/**
 * Codle — Registration & Login
 * Application Script
 *
 * Features:
 * - Login / Registration toggle
 * - Multi-step registration wizard
 * - Adaptive quiz engine (10 questions, difficulty adjusts based on answers)
 * - Email verification with 6-digit code simulation
 * - Username availability checking (simulated)
 * - Password strength meter with rule validation
 * - Floating particle background
 */

(function () {
  "use strict";

  /* ===============================================================
     0. QUESTION BANK — Adaptive Quiz Data
  ================================================================*/

  var QUESTIONS = {
    html: [
      // Level 1 — Beginner
      { level: 1, q: "What does HTML stand for?", answers: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"], correct: 0 },
      { level: 1, q: "Which tag is used for the highest level heading?", answers: ["<heading>", "<h6>", "<h1>", "<head>"], correct: 2 },
      { level: 1, q: "Which HTML element is used for paragraphs?", answers: ["<paragraph>", "<p>", "<text>", "<br>"], correct: 1 },
      // Level 2
      { level: 2, q: "What is the correct HTML element for inserting an image?", code: null, answers: ["<img src=\"image.jpg\">", "<image src=\"image.jpg\">", "<picture>image.jpg</picture>", "<src img=\"image.jpg\">"], correct: 0 },
      { level: 2, q: "What does the 'alt' attribute do on the <img> tag?", answers: ["Sets an alternative image", "Describes the image for accessibility", "Resizes the image", "Adds an animation"], correct: 1 },
      { level: 2, q: "Which HTML element creates a numbered list?", answers: ["<ul>", "<list>", "<ol>", "<dl>"], correct: 2 },
      // Level 3
      { level: 3, q: "What is the purpose of the <meta charset=\"UTF-8\"> tag?", answers: ["Sets the page language", "Defines the character set of the document", "Adds metadata for SEO", "Sets the password encoding"], correct: 1 },
      { level: 3, q: "What is semantic HTML?", answers: ["HTML with inline styles", "Using tags that clearly describe their content", "HTML validated by W3C validator", "HTML generated by JavaScript"], correct: 1 },
      { level: 3, q: "What is the difference between <section> and <div>?", answers: ["No difference", "<section> is semantic, <div> has no meaning", "<div> is semantic, <section> is not", "<section> is deprecated"], correct: 1 },
      // Level 4
      { level: 4, q: "What does the loading=\"lazy\" attribute do for images?", answers: ["Loads the image asynchronously", "Defers loading the image until it is near the viewport", "Compresses the image", "Loads the image from cache"], correct: 1 },
      { level: 4, q: "What is the purpose of the <template> tag?", answers: ["Defines a page template", "Holds HTML content hidden from the user when the page loads", "Creates a responsive layout", "Imports external HTML"], correct: 1 },
      // Level 5
      { level: 5, q: "What is the Shadow DOM?", answers: ["DOM of shadow elements on the page", "Encapsulated DOM separate from the main document", "Invisible DOM elements", "Alternative to Virtual DOM"], correct: 1 },
      { level: 5, q: "What does the contenteditable attribute do?", code: '<div contenteditable="true">Text</div>', answers: ["Locks the content from being edited", "Allows the user to edit the element's content", "Allows text copying", "Encrypts the element content"], correct: 1 },
    ],

    css: [
      // Level 1
      { level: 1, q: "How do you set text color in CSS?", answers: ["text-color: red;", "font-color: red;", "color: red;", "text: red;"], correct: 2 },
      { level: 1, q: "Which CSS selector targets an element with id 'header'?", answers: [".header", "#header", "header", "*header"], correct: 1 },
      { level: 1, q: "How do you add a comment in CSS?", answers: ["// comment", "<!-- comment -->", "/* comment */", "# comment"], correct: 2 },
      // Level 2
      { level: 2, q: "What does 'display: flex' do?", answers: ["Hides the element", "Creates a flexible container", "Sets a fixed position", "Creates a grid layout"], correct: 1 },
      { level: 2, q: "What is the difference between margin and padding?", answers: ["None", "Margin is outer space, padding is inner space", "Padding is outer space, margin is inner space", "Both are inner spaces"], correct: 1 },
      { level: 2, q: "What does 'position: relative' do?", answers: ["Removes element from normal flow", "Element remains in normal flow but can be offset", "Element is fixed to the screen", "Centers the element"], correct: 1 },
      // Level 3
      { level: 3, q: "What is CSS specificity? Order from lowest to highest:", answers: ["element < class < id < inline", "class < element < id < inline", "id < class < element < inline", "inline < id < class < element"], correct: 0 },
      { level: 3, q: "What does 'box-sizing: border-box' do?", answers: ["Adds a border to every element", "Width and height include padding and border", "Removes the box model", "Sets rounded corners"], correct: 1 },
      { level: 3, q: "How does 'z-index' work?", answers: ["Sets the font size", "Controls the stacking order of elements", "Sets the transparency", "Defines a grid zone"], correct: 1 },
      // Level 4
      { level: 4, q: "What is 'CSS Grid' and how does it differ from Flexbox?", answers: ["Grid is only for tables", "Grid is a 2D system, Flexbox is 1D", "Grid is deprecated, Flexbox is modern", "No difference"], correct: 1 },
      { level: 4, q: "What does the CSS function clamp() do?", code: "font-size: clamp(1rem, 2.5vw, 3rem);", answers: ["Restricts a value between a minimum and maximum", "Rounds the value", "Animates between values", "Converts units"], correct: 0 },
      // Level 5
      { level: 5, q: "What is a CSS @container query?", answers: ["Query for a database", "Styling based on the size of a parent container", "Media query for Docker containers", "Alternative to @media"], correct: 1 },
      { level: 5, q: "How does the CSS pseudo-class :has() work?", code: "div:has(> img) { border: 1px solid; }", answers: ["Selects a div inside an img", "Selects a div that contains a direct child img", "Selects an img inside a div", "Adds an image to a div"], correct: 1 },
    ],

    javascript: [
      // Level 1
      { level: 1, q: "How do you declare a variable in JavaScript?", answers: ["variable x = 5;", "var x = 5;", "v x = 5;", "x := 5;"], correct: 1 },
      { level: 1, q: "What is the output of this code?", code: "console.log(typeof 42);", answers: ["\"integer\"", "\"number\"", "\"float\"", "\"num\""], correct: 1 },
      { level: 1, q: "What does 'console.log()' do?", answers: ["Writes to a file", "Prints to the browser console", "Creates a dialog box", "Logs server errors"], correct: 1 },
      // Level 2
      { level: 2, q: "What is the difference between '==' and '==='?", answers: ["None", "'==' also compares types", "'===' compares both value and type", "'===' is deprecated"], correct: 2 },
      { level: 2, q: "What does this expression return?", code: "[1, 2, 3].map(x => x * 2);", answers: ["[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "6", "[1, 4, 9]"], correct: 0 },
      { level: 2, q: "What is a callback function?", answers: ["A function that calls itself", "A function passed as an argument to another function", "A function returning void", "A recursive function"], correct: 1 },
      // Level 3
      { level: 3, q: "What is a closure in JavaScript?", answers: ["A way to close the browser", "A function with access to variables in its outer scope", "Syntactic sugar for classes", "A method for closing connections"], correct: 1 },
      { level: 3, q: "What does this code output?", code: "let a = [1,2,3];\nlet b = a;\nb.push(4);\nconsole.log(a.length);", answers: ["3", "4", "undefined", "Error"], correct: 1 },
      { level: 3, q: "What is the difference between 'let' and 'var'?", answers: ["No difference", "'let' has block scope, 'var' has function scope", "'var' has block scope, 'let' has function scope", "'let' is faster"], correct: 1 },
      // Level 4
      { level: 4, q: "What does 'Promise.all()' do?", answers: ["Executes promises sequentially", "Waits for all promises to be fulfilled", "Cancels all promises", "Returns the first fulfilled promise"], correct: 1 },
      { level: 4, q: "What is the event loop?", answers: ["A loop for DOM event handling", "A mechanism for processing asynchronous tasks", "An infinite loop in the browser", "A method for repeating animations"], correct: 1 },
      // Level 5
      { level: 5, q: "What is a Proxy object in JavaScript?", answers: ["An HTTP proxy server", "An object for intercepting and defining custom operations", "A design pattern for lazy loading", "A wrapper for localStorage"], correct: 1 },
      { level: 5, q: "What does this code output?", code: "async function* gen() {\n  yield await Promise.resolve(1);\n  yield await Promise.resolve(2);\n}\nconst g = gen();\nconsole.log((await g.next()).value);", answers: ["undefined", "1", "Promise {1}", "[1, 2]"], correct: 1 },
    ],

    php: [
      // Level 1
      { level: 1, q: "How does a PHP block of code start?", answers: ["<script>", "<?php", "<php>", "<%"], correct: 1 },
      { level: 1, q: "How do you declare a variable in PHP?", answers: ["var name;", "$name;", "let name;", "dim name;"], correct: 1 },
      { level: 1, q: "How do you output text in PHP?", answers: ["print(\"text\")", "echo \"text\";", "write(\"text\")", "All are correct"], correct: 3 },
      // Level 2
      { level: 2, q: "What is the difference between echo and print in PHP?", answers: ["None", "echo has no return value, print does", "print is faster", "echo only accepts strings"], correct: 1 },
      { level: 2, q: "How do you create an associative array?", code: null, answers: ["$arr = array(\"key\" => \"value\");", "$arr = [key: value];", "$arr = {\"key\": \"value\"};", "$arr = array(key, value);"], correct: 0 },
      { level: 2, q: "What does the isset() function do?", answers: ["Sets a variable", "Checks if a variable is set and is not NULL", "Deletes a variable", "Returns the variable type"], correct: 1 },
      // Level 3
      { level: 3, q: "What are PHP namespaces?", answers: ["Spaces for storing files", "Code organization to prevent name collisions", "Alternative to classes", "Configuration files"], correct: 1 },
      { level: 3, q: "What is the difference between include and require?", answers: ["None", "require stops the script on error, include does not", "include stops the script on error, require does not", "require is faster"], correct: 1 },
      { level: 3, q: "What are PHP traits?", answers: ["Data types", "A mechanism for code reuse in classes", "Server configuration", "Testing frameworks"], correct: 1 },
      // Level 4
      { level: 4, q: "What is PDO in PHP?", answers: ["A templating system", "An abstraction for database access", "A WordPress plugin", "A formatting tool"], correct: 1 },
      { level: 4, q: "What does a generator do in PHP?", code: "function gen() {\n  yield 1;\n  yield 2;\n  yield 3;\n}", answers: ["Creates an array [1,2,3]", "A function that returns an iterable sequence lazily", "Generates random numbers", "Compiles PHP to bytecode"], correct: 1 },
      // Level 5
      { level: 5, q: "What are PHP Fibers (PHP 8.1)?", answers: ["Threads for parallel processing", "Cooperative multitasking with a suspendable stack", "A logging system", "A micro-services framework"], correct: 1 },
      { level: 5, q: "What does the #[Pure] attribute do in PHP 8?", answers: ["Marks a method as having no side-effects", "Clears the output buffer", "Sanitizes inputs", "Optimizes performance"], correct: 0 },
    ]
  };

  /* Simulated list of taken usernames */
  var TAKEN_USERNAMES = [
    "admin", "codle", "codemaster", "user", "test", "root", "system",
    "moderator", "developer", "python", "javascript", "webdev", "hacker",
    "john", "jane", "alex", "programmer", "null", "undefined"
  ];

  /* Simulated verification code */
  var VERIFICATION_CODE = "111111"; // Hardcoded per user request

  /* ===============================================================
     1. PARTICLES BACKGROUND
  ================================================================*/

  (function initParticles() {
    var canvas = document.getElementById("particles-canvas");
    if (!canvas) return;
    var ctx = canvas.getContext("2d");
    var particles = [];
    var particleCount = 60;

    function resize() {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    }
    resize();
    window.addEventListener("resize", resize);

    function Particle() {
      this.x = Math.random() * canvas.width;
      this.y = Math.random() * canvas.height;
      this.vx = (Math.random() - 0.5) * 0.3;
      this.vy = (Math.random() - 0.5) * 0.3;
      this.r = Math.random() * 2 + 0.5;
      this.alpha = Math.random() * 0.4 + 0.1;
    }

    for (var i = 0; i < particleCount; i++) {
      particles.push(new Particle());
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      particles.forEach(function (p) {
        p.x += p.vx;
        p.y += p.vy;
        if (p.x < 0 || p.x > canvas.width) p.vx *= -1;
        if (p.y < 0 || p.y > canvas.height) p.vy *= -1;

        ctx.beginPath();
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(255, 255, 255, " + p.alpha + ")";
        ctx.fill();
      });

      // Draw connections
      for (var i = 0; i < particles.length; i++) {
        for (var j = i + 1; j < particles.length; j++) {
          var dx = particles[i].x - particles[j].x;
          var dy = particles[i].y - particles[j].y;
          var dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 120) {
            ctx.beginPath();
            ctx.moveTo(particles[i].x, particles[i].y);
            ctx.lineTo(particles[j].x, particles[j].y);
            ctx.strokeStyle = "rgba(255, 255, 255, " + (0.06 * (1 - dist / 120)) + ")";
            ctx.lineWidth = 0.5;
            ctx.stroke();
          }
        }
      }
      requestAnimationFrame(animate);
    }

    if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      animate();
    }
  })();

  /* ===============================================================
     2. AUTH TOGGLE (Login / Register)
  ================================================================*/

  var toggleRegister = document.getElementById("toggle-register");
  var toggleLogin = document.getElementById("toggle-login");
  var slider = document.getElementById("auth-toggle-slider");
  var loginView = document.getElementById("login-view");
  var registerView = document.getElementById("register-view");

  function updateToggle() {
    var activeBtn = document.querySelector(".auth-toggle-btn.active");
    if (!activeBtn || !slider) return;
    slider.style.width = activeBtn.offsetWidth + "px";
    slider.style.transform = "translateX(" + activeBtn.offsetLeft + "px)";
  }

  if (toggleRegister) {
    toggleRegister.addEventListener("click", function () {
      toggleRegister.classList.add("active");
      toggleLogin.classList.remove("active");
      registerView.style.display = "";
      registerView.style.animation = "fadeSlideUp .5s var(--lg-spring) both";
      loginView.style.display = "none";
      updateToggle();
    });
  }
  if (toggleLogin) {
    toggleLogin.addEventListener("click", function () {
      toggleLogin.classList.add("active");
      toggleRegister.classList.remove("active");
      loginView.style.display = "";
      loginView.style.animation = "fadeSlideUp .5s var(--lg-spring) both";
      registerView.style.display = "none";
      updateToggle();
    });
  }

  window.addEventListener("load", updateToggle);
  window.addEventListener("resize", updateToggle);

  /* ===============================================================
     3. LOGIN FORM
  ================================================================*/

  var loginForm = document.getElementById("login-form");
  if (loginForm) {
    loginForm.addEventListener("submit", function (e) {
      e.preventDefault();
      var email = document.getElementById("login-email").value.trim();
      var pass = document.getElementById("login-password").value;
      var valid = true;

      // Email validation
      var emailGroup = document.getElementById("login-email-group");
      var emailError = document.getElementById("login-email-error");
      if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        emailGroup.classList.add("invalid");
        emailGroup.classList.remove("valid");
        emailError.textContent = "Please enter a valid e-mail";
        valid = false;
      } else {
        emailGroup.classList.remove("invalid");
        emailGroup.classList.add("valid");
        emailError.textContent = "";
      }

      // Password validation
      var passGroup = document.getElementById("login-password-group");
      var passError = document.getElementById("login-password-error");
      if (!pass) {
        passGroup.classList.add("invalid");
        passGroup.classList.remove("valid");
        passError.textContent = "Please enter your password";
        valid = false;
      } else {
        passGroup.classList.remove("invalid");
        passGroup.classList.add("valid");
        passError.textContent = "";
      }

      if (valid) {
        var btn = document.getElementById("login-submit");
        btn.classList.add("loading");
        btn.disabled = true;
        setTimeout(function () {
          // Simulated login — redirect to main app
          window.location.href = "index.html";
        }, 1500);
      }
    });
  }

  // Toggle password visibility for login
  var loginToggleVis = document.getElementById("login-toggle-vis");
  if (loginToggleVis) {
    loginToggleVis.addEventListener("click", function () {
      var inp = document.getElementById("login-password");
      inp.type = inp.type === "password" ? "text" : "password";
      loginToggleVis.querySelector("svg").style.color =
        inp.type === "text" ? "var(--accent)" : "";
    });
  }

  /* ===============================================================
     4. REGISTRATION WIZARD
  ================================================================*/

  var currentStep = 1;
  var selectedLang = null;
  var quizState = {
    lang: null,
    questionIndex: 0,
    currentDifficulty: 1,
    score: 0,
    correct: 0,
    wrong: 0,
    answered: false,
    questions: [],
    startTime: null
  };
  var emailVerified = false;
  var usernameValid = false;
  var passwordValid = false;
  var confirmValid = false;

  function goToStep(step) {
    // Hide all panels
    document.querySelectorAll(".wizard-panel").forEach(function (p) {
      p.classList.remove("active");
    });

    // Show target panel
    var targetId = "step-" + step;
    if (step === "2-results") targetId = "step-2-results";
    if (step === "success") targetId = "step-success";
    var target = document.getElementById(targetId);
    if (target) {
      target.classList.add("active");
      target.style.animation = "panelIn .5s var(--lg-spring) both";
    }

    // Update progress dots
    var numericStep = parseInt(step) || currentStep;
    document.querySelectorAll(".wizard-step").forEach(function (s) {
      var sStep = parseInt(s.dataset.step);
      s.classList.remove("active", "completed");
      if (sStep < numericStep) s.classList.add("completed");
      else if (sStep === numericStep) s.classList.add("active");
    });

    // Update progress bar
    var progressEl = document.getElementById("wizard-progress");
    if (progressEl) progressEl.dataset.progress = numericStep;

    // Hide progress on success
    if (step === "success") {
      progressEl.style.display = "none";
    }

    currentStep = numericStep;
  }

  /* ===== STEP 1: Language Selection ===== */
  var langCards = document.querySelectorAll(".lang-card");
  var btnStartQuiz = document.getElementById("btn-start-quiz");

  var brandColors = {
    html: { a1: "#e34f26", a2: "#f16529" },
    css: { a1: "#1572b6", a2: "#33a9dc" },
    javascript: { a1: "#f7df1e", a2: "#f9e64f" },
    php: { a1: "#777bb4", a2: "#8892bf" }
  };

  langCards.forEach(function (card) {
    card.addEventListener("click", function () {
      langCards.forEach(function (c) { c.classList.remove("selected"); });
      card.classList.add("selected");
      selectedLang = card.dataset.lang;
      btnStartQuiz.disabled = false;
      
      // Dynamicky změnit accent barvu podle jazyka
      var colors = brandColors[selectedLang];
      if (colors) {
        document.documentElement.style.setProperty("--accent", colors.a1);
        document.documentElement.style.setProperty("--accent-2", colors.a2);
      }
    });
  });

  if (btnStartQuiz) {
    btnStartQuiz.addEventListener("click", function () {
      if (!selectedLang) return;
      initQuiz(selectedLang);
      goToStep(2);
    });
  }

  /* ===== STEP 2: Adaptive Quiz Engine ===== */

  function initQuiz(lang) {
    quizState.lang = lang;
    quizState.questionIndex = 0;
    quizState.currentDifficulty = 1;
    quizState.score = 0;
    quizState.correct = 0;
    quizState.wrong = 0;
    quizState.answered = false;
    quizState.startTime = Date.now();

    // Build adaptive question list
    var pool = QUESTIONS[lang] || [];
    quizState.questions = selectAdaptiveQuestions(pool, 10);

    // Update UI
    document.getElementById("quiz-lang-name").textContent = langDisplayName(lang);
    document.getElementById("quiz-total").textContent = quizState.questions.length;

    showQuestion(0);
  }

  function langDisplayName(lang) {
    var names = { html: "HTML", css: "CSS", javascript: "JavaScript", php: "PHP" };
    return names[lang] || lang;
  }

  /**
   * Adaptive question selection algorithm.
   * Starts with easy questions, adjusts difficulty based on performance.
   * Returns an ordered list of 10 questions from the pool.
   */
  function selectAdaptiveQuestions(pool, count) {
    // Sort pool by level
    var byLevel = {};
    pool.forEach(function (q) {
      if (!byLevel[q.level]) byLevel[q.level] = [];
      byLevel[q.level].push(q);
    });

    // Shuffle within each level
    Object.keys(byLevel).forEach(function (lvl) {
      byLevel[lvl] = shuffleArray(byLevel[lvl]);
    });

    // Pick questions adaptively — we'll start at level 1 and adjust
    var selected = [];
    var difficulty = 1;
    var used = {};

    for (var i = 0; i < count; i++) {
      // Try to find a question at current difficulty
      var candidates = (byLevel[difficulty] || []).filter(function (q) { return !used[q.q]; });

      // If no candidates at current level, look nearby
      if (candidates.length === 0) {
        for (var delta = 1; delta <= 5; delta++) {
          candidates = (byLevel[difficulty + delta] || []).filter(function (q) { return !used[q.q]; });
          if (candidates.length > 0) break;
          candidates = (byLevel[Math.max(1, difficulty - delta)] || []).filter(function (q) { return !used[q.q]; });
          if (candidates.length > 0) break;
        }
      }

      if (candidates.length === 0) break;

      var pick = candidates[0];
      selected.push(pick);
      used[pick.q] = true;

      // Adaptive: after every 2 questions, potentially increase difficulty
      if ((i + 1) % 2 === 0) {
        difficulty = Math.min(5, difficulty + 1);
      }
    }

    return selected;
  }

  function shuffleArray(arr) {
    var a = arr.slice();
    for (var i = a.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = a[i];
      a[i] = a[j];
      a[j] = tmp;
    }
    return a;
  }

  function showQuestion(idx) {
    var q = quizState.questions[idx];
    if (!q) return;

    quizState.answered = false;
    document.getElementById("quiz-current").textContent = idx + 1;
    document.getElementById("quiz-progress-fill").style.width =
      ((idx + 1) / quizState.questions.length * 100) + "%";

    // Difficulty indicator
    updateDifficultyIndicator(q.level);

    // Question
    document.getElementById("quiz-question").textContent = q.q;

    // Code block
    var codeBlock = document.getElementById("quiz-code-block");
    var codeEl = document.getElementById("quiz-code");
    if (q.code) {
      codeEl.textContent = q.code;
      codeBlock.style.display = "block";
    } else {
      codeBlock.style.display = "none";
    }

    // Answers
    var answersContainer = document.getElementById("quiz-answers");
    answersContainer.innerHTML = "";
    var letters = ["A", "B", "C", "D"];
    q.answers.forEach(function (ans, i) {
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "quiz-answer";
      btn.dataset.idx = i;
      btn.innerHTML = '<span class="answer-letter">' + letters[i] + '</span><span>' + ans + '</span>';
      btn.addEventListener("click", function () { handleAnswer(idx, i); });
      answersContainer.appendChild(btn);
    });

    // Hide feedback
    var feedback = document.getElementById("quiz-feedback");
    feedback.style.display = "none";

    // Disable next button
    document.getElementById("btn-quiz-next").disabled = true;
  }

  function updateDifficultyIndicator(level) {
    var labels = { 1: "Beginner", 2: "Basics", 3: "Intermediate", 4: "Advanced", 5: "Master" };
    document.getElementById("difficulty-label").textContent = labels[level] || "???";
    document.querySelectorAll(".diff-dot").forEach(function (dot) {
      var dotLevel = parseInt(dot.dataset.level);
      dot.classList.toggle("active", dotLevel <= level);
    });
  }

  function handleAnswer(questionIdx, answerIdx) {
    if (quizState.answered) return;
    quizState.answered = true;

    var q = quizState.questions[questionIdx];
    var isCorrect = answerIdx === q.correct;

    // Mark answers
    var answerBtns = document.querySelectorAll(".quiz-answer");
    answerBtns.forEach(function (btn) {
      btn.classList.add("disabled");
      var bIdx = parseInt(btn.dataset.idx);
      if (bIdx === q.correct) {
        btn.classList.add("correct");
      }
      if (bIdx === answerIdx && !isCorrect) {
        btn.classList.add("wrong");
      }
      if (bIdx === answerIdx) {
        btn.classList.add("selected");
      }
    });

    // Show feedback
    var feedback = document.getElementById("quiz-feedback");
    feedback.style.display = "flex";
    feedback.style.animation = "feedbackIn .4s var(--lg-spring) both";
    var feedbackIcon = document.getElementById("feedback-icon");
    var feedbackText = document.getElementById("feedback-text");

    if (isCorrect) {
      feedback.className = "quiz-feedback correct";
      feedbackIcon.textContent = "✓";
      feedbackText.textContent = "Correct! Well done!";
      quizState.correct++;
      quizState.score += q.level * 10;
      // Increase difficulty
      quizState.currentDifficulty = Math.min(5, quizState.currentDifficulty + 1);
    } else {
      feedback.className = "quiz-feedback wrong";
      feedbackIcon.textContent = "✗";
      feedbackText.textContent = "Incorrect. The correct answer was: " + q.answers[q.correct];
      quizState.wrong++;
      // Decrease difficulty
      quizState.currentDifficulty = Math.max(1, quizState.currentDifficulty - 1);
    }

    // Enable next button
    var btnNext = document.getElementById("btn-quiz-next");
    btnNext.disabled = false;

    // Update next question difficulty if applicable
    if (questionIdx + 1 < quizState.questions.length) {
      btnNext.querySelector(".btn-text").textContent = "Next Question";
    } else {
      btnNext.querySelector(".btn-text").textContent = "Show Results";
    }
  }

  var btnQuizNext = document.getElementById("btn-quiz-next");
  if (btnQuizNext) {
    btnQuizNext.addEventListener("click", function () {
      quizState.questionIndex++;
      if (quizState.questionIndex < quizState.questions.length) {
        showQuestion(quizState.questionIndex);
      } else {
        showQuizResults();
      }
    });
  }

  var btnQuizBack = document.getElementById("btn-quiz-back");
  if (btnQuizBack) {
    btnQuizBack.addEventListener("click", function () {
      goToStep(1);
    });
  }

  function showQuizResults() {
    var total = quizState.questions.length;
    var pct = Math.round((quizState.correct / total) * 100);
    var elapsed = Math.round((Date.now() - quizState.startTime) / 1000);

    // Determine level
    var level = "Beginner";
    if (pct >= 90) level = "Master";
    else if (pct >= 70) level = "Advanced";
    else if (pct >= 50) level = "Intermediate";
    else if (pct >= 30) level = "Basics";

    goToStep("2-results");

    document.getElementById("results-score").textContent = pct + "%";
    document.getElementById("results-correct").textContent = quizState.correct;
    document.getElementById("results-wrong").textContent = quizState.wrong;
    document.getElementById("results-time").textContent = elapsed + "s";
    document.getElementById("results-level-name").textContent = level;

    // Determine title
    if (pct >= 80) document.getElementById("results-title").textContent = "Great job! 🎉";
    else if (pct >= 50) document.getElementById("results-title").textContent = "Well done! 👍";
    else document.getElementById("results-title").textContent = "Good start! 💪";

    // Animate ring
    setTimeout(function () {
      var ring = document.getElementById("results-ring-fill");
      var offset = 327 - (327 * pct / 100);
      ring.style.transition = "stroke-dashoffset 1.5s var(--lg-spring)";
      ring.style.strokeDashoffset = offset;
    }, 100);

    // Update step 2 as completed in progress
    var step2dot = document.querySelector('.wizard-step[data-step="2"]');
    if (step2dot) {
      step2dot.classList.add("completed");
      step2dot.classList.remove("active");
    }
  }

  var btnToEmail = document.getElementById("btn-to-email");
  if (btnToEmail) {
    btnToEmail.addEventListener("click", function () {
      goToStep(3);
    });
  }

  /* ===== STEP 3: Email Verification ===== */

  var regEmail = document.getElementById("reg-email");
  var btnSendCode = document.getElementById("btn-send-code");
  var verifySection = document.getElementById("verify-code-section");

  // Enable send button when valid email entered
  if (regEmail) {
    regEmail.addEventListener("input", function () {
      var val = regEmail.value.trim();
      var isValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val);
      btnSendCode.disabled = !isValid;

      var group = document.getElementById("reg-email-group");
      var error = document.getElementById("reg-email-error");
      if (val && !isValid) {
        group.classList.add("invalid");
        group.classList.remove("valid");
        error.textContent = "Please enter a valid e-mail";
      } else if (isValid) {
        group.classList.remove("invalid");
        group.classList.add("valid");
        error.textContent = "";
      } else {
        group.classList.remove("invalid", "valid");
        error.textContent = "";
      }
    });
  }

  if (btnSendCode) {
    btnSendCode.addEventListener("click", function () {
      var email = regEmail.value.trim();
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return;

      // Verification code is hardcoded to 111111 per user instructions
      VERIFICATION_CODE = "111111";
      console.log("📧 Verification code (simulation):", VERIFICATION_CODE);

      // Show verification section
      verifySection.style.display = "block";
      document.getElementById("verify-email-display").textContent = email;

      // Update button
      btnSendCode.textContent = "Sent ✓";
      btnSendCode.classList.add("sent");
      btnSendCode.disabled = true;

      // Start resend countdown
      startResendTimer();

      // Focus first code digit
      setTimeout(function () {
        document.getElementById("code-digit-0").focus();
      }, 300);
    });
  }

  // Code digit inputs
  var codeDigits = document.querySelectorAll(".code-digit");
  codeDigits.forEach(function (digit, idx) {
    digit.addEventListener("input", function (e) {
      var val = e.target.value.replace(/[^0-9]/g, "");
      e.target.value = val;
      if (val) {
        e.target.classList.add("filled");
        // Auto-focus next
        if (idx < 5) {
          codeDigits[idx + 1].focus();
        }
        // Check if all filled
        checkVerificationCode();
      }
    });

    digit.addEventListener("keydown", function (e) {
      if (e.key === "Backspace" && !e.target.value && idx > 0) {
        codeDigits[idx - 1].focus();
        codeDigits[idx - 1].value = "";
        codeDigits[idx - 1].classList.remove("filled");
      }
    });

    // Allow paste of full code
    digit.addEventListener("paste", function (e) {
      e.preventDefault();
      var paste = (e.clipboardData || window.clipboardData).getData("text").replace(/\D/g, "");
      if (paste.length >= 6) {
        for (var i = 0; i < 6; i++) {
          codeDigits[i].value = paste[i] || "";
          if (paste[i]) codeDigits[i].classList.add("filled");
        }
        codeDigits[5].focus();
        checkVerificationCode();
      }
    });
  });

  function checkVerificationCode() {
    var code = "";
    codeDigits.forEach(function (d) { code += d.value; });
    if (code.length < 6) return;

    var status = document.getElementById("verify-status");
    var btnContinue = document.getElementById("btn-to-account");

    if (code === VERIFICATION_CODE) {
      status.className = "verify-status success";
      status.textContent = "✓ E-mail verified successfully!";
      emailVerified = true;
      btnContinue.disabled = false;
      codeDigits.forEach(function (d) { d.classList.add("correct"); d.disabled = true; });
    } else {
      status.className = "verify-status error";
      status.textContent = "✗ Incorrect code. Try again.";
      codeDigits.forEach(function (d) { d.classList.add("wrong"); });
      // Shake and reset after delay
      setTimeout(function () {
        codeDigits.forEach(function (d) {
          d.value = "";
          d.classList.remove("filled", "wrong");
        });
        codeDigits[0].focus();
        status.textContent = "";
      }, 1200);
    }
  }

  function startResendTimer() {
    var timer = 60;
    var timerEl = document.getElementById("resend-timer");
    var btnResend = document.getElementById("btn-resend");
    btnResend.disabled = true;

    var iv = setInterval(function () {
      timer--;
      timerEl.textContent = timer;
      if (timer <= 0) {
        clearInterval(iv);
        btnResend.disabled = false;
        btnResend.innerHTML = "Resend Code";
      }
    }, 1000);
  }

  var btnResend = document.getElementById("btn-resend");
  if (btnResend) {
    btnResend.addEventListener("click", function () {
      VERIFICATION_CODE = "111111"; // Still hardcoded
      console.log("📧 New verification code (simulation):", VERIFICATION_CODE);
      btnResend.innerHTML = 'Resend in <span id="resend-timer">60</span>s';
      startResendTimer();
      // Reset digits
      codeDigits.forEach(function (d) {
        d.value = "";
        d.classList.remove("filled", "correct", "wrong");
        d.disabled = false;
      });
      document.getElementById("verify-status").textContent = "";
      codeDigits[0].focus();
    });
  }

  var btnToAccount = document.getElementById("btn-to-account");
  if (btnToAccount) {
    btnToAccount.addEventListener("click", function () {
      if (!emailVerified) return;
      goToStep(4);
    });
  }

  var btnEmailBack = document.getElementById("btn-email-back");
  if (btnEmailBack) {
    btnEmailBack.addEventListener("click", function () {
      goToStep("2-results");
    });
  }

  /* ===== STEP 4: Username & Password ===== */

  var regUsername = document.getElementById("reg-username");
  var regPassword = document.getElementById("reg-password");
  var regConfirm = document.getElementById("reg-confirm");
  var usernameTimer = null;

  // Username validation
  if (regUsername) {
    regUsername.addEventListener("input", function () {
      var val = regUsername.value.trim();
      var group = document.getElementById("reg-username-group");
      var error = document.getElementById("reg-username-error");
      var status = document.getElementById("username-status");

      usernameValid = false;
      updateCreateButton();

      if (!val) {
        group.classList.remove("valid", "invalid");
        error.textContent = "";
        status.style.display = "none";
        return;
      }

      // Format validation
      if (val.length < 3) {
        group.classList.add("invalid");
        group.classList.remove("valid");
        error.textContent = "Minimum 3 characters";
        status.style.display = "none";
        return;
      }
      if (val.length > 20) {
        group.classList.add("invalid");
        group.classList.remove("valid");
        error.textContent = "Maximum 20 characters";
        status.style.display = "none";
        return;
      }
      if (!/^[a-zA-Z0-9_]+$/.test(val)) {
        group.classList.add("invalid");
        group.classList.remove("valid");
        error.textContent = "Only letters, numbers, and underscores allowed";
        status.style.display = "none";
        return;
      }

      // Simulated availability check (with debounce)
      group.classList.remove("valid", "invalid");
      error.textContent = "";
      status.style.display = "flex";
      status.innerHTML = '<div class="spinner-sm"></div>';

      clearTimeout(usernameTimer);
      usernameTimer = setTimeout(function () {
        var taken = TAKEN_USERNAMES.indexOf(val.toLowerCase()) !== -1;
        if (taken) {
          group.classList.add("invalid");
          group.classList.remove("valid");
          error.textContent = "This username is already taken";
          status.style.display = "flex";
          status.innerHTML = '<span style="color:var(--error);font-size:16px;">✗</span>';
          usernameValid = false;
        } else {
          group.classList.add("valid");
          group.classList.remove("invalid");
          error.textContent = "";
          status.style.display = "flex";
          status.innerHTML = '<span style="color:var(--success);font-size:16px;">✓</span>';
          usernameValid = true;
        }
        updateCreateButton();
      }, 800);
    });
  }

  // Password validation
  if (regPassword) {
    regPassword.addEventListener("input", function () {
      var val = regPassword.value;
      var rules = {
        length: val.length >= 8,
        upper: /[A-Z]/.test(val),
        lower: /[a-z]/.test(val),
        number: /[0-9]/.test(val),
        special: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(val)
      };

      var metCount = 0;
      Object.keys(rules).forEach(function (key) {
        var el = document.getElementById("rule-" + key);
        if (rules[key]) {
          el.classList.add("met");
          el.querySelector(".rule-icon").textContent = "✓";
          metCount++;
        } else {
          el.classList.remove("met");
          el.querySelector(".rule-icon").textContent = "○";
        }
      });

      // Strength meter
      var fill = document.getElementById("strength-fill");
      var label = document.getElementById("strength-label");
      fill.dataset.level = metCount;

      var labels = ["", "Very Weak", "Weak", "Fair", "Strong", "Very Strong"];
      var colors = ["", "var(--error)", "var(--coral)", "var(--warning)", "var(--accent)", "var(--success)"];
      label.textContent = val ? labels[metCount] : "Enter password";
      label.style.color = colors[metCount] || "";

      passwordValid = metCount === 5;

      // Check confirm match
      checkPasswordMatch();
      updateCreateButton();
    });
  }

  // Toggle password visibility for register
  var regToggleVis = document.getElementById("reg-toggle-vis");
  if (regToggleVis) {
    regToggleVis.addEventListener("click", function () {
      var inp = document.getElementById("reg-password");
      inp.type = inp.type === "password" ? "text" : "password";
      regToggleVis.querySelector("svg").style.color =
        inp.type === "text" ? "var(--accent)" : "";
    });
  }

  // Password confirmation
  if (regConfirm) {
    regConfirm.addEventListener("input", function () {
      checkPasswordMatch();
      updateCreateButton();
    });
  }

  function checkPasswordMatch() {
    var pass = document.getElementById("reg-password").value;
    var conf = document.getElementById("reg-confirm").value;
    var group = document.getElementById("reg-confirm-group");
    var error = document.getElementById("reg-confirm-error");

    if (!conf) {
      group.classList.remove("valid", "invalid");
      error.textContent = "";
      confirmValid = false;
      return;
    }

    if (pass === conf) {
      group.classList.add("valid");
      group.classList.remove("invalid");
      error.textContent = "";
      confirmValid = true;
    } else {
      group.classList.add("invalid");
      group.classList.remove("valid");
      error.textContent = "Passwords do not match";
      confirmValid = false;
    }
  }

  function updateCreateButton() {
    var btn = document.getElementById("btn-create-account");
    btn.disabled = !(usernameValid && passwordValid && confirmValid);
  }

  var btnAccountBack = document.getElementById("btn-account-back");
  if (btnAccountBack) {
    btnAccountBack.addEventListener("click", function () {
      goToStep(3);
    });
  }

  // Account form submit
  var accountForm = document.getElementById("account-form");
  if (accountForm) {
    accountForm.addEventListener("submit", function (e) {
      e.preventDefault();
      if (!(usernameValid && passwordValid && confirmValid)) return;

      var btn = document.getElementById("btn-create-account");
      btn.classList.add("loading");
      btn.disabled = true;

      var username = document.getElementById("reg-username").value.trim();

      setTimeout(function () {
        // Show success
        document.getElementById("success-username").textContent = username;
        goToStep("success");
        animateSuccess();
      }, 2000);
    });
  }

  function animateSuccess() {
    setTimeout(function () {
      var circle = document.getElementById("success-circle");
      circle.style.transition = "stroke-dashoffset 1s var(--lg-spring)";
      circle.style.strokeDashoffset = "0";

      setTimeout(function () {
        var check = document.getElementById("success-checkmark");
        check.style.transition = "stroke-dashoffset .6s var(--lg-spring)";
        check.style.strokeDashoffset = "0";
      }, 600);
    }, 200);
  }

})();
